name: smokequit
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  google_fonts: any
  world_countries: any
  tflite_v2: ^1.0.0
#  tflite:
  image_picker:
  tflite_flutter: ^0.10.1
  camera:
  image: ^3.3.0
  tflite_flutter_helper_plus: ^0.0.2
  tflite_flutter_plus:
#  tflite:
  wikipedia: ^0.0.7
  http: ^0.13.5
  file_picker: ^5.3.3
  ffi: ^2.0.1

dev_dependencies:

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/smokquit-logo-1.png
    - assets/page-1/images/icon-lock-locked.png
    - assets/page-1/images/polygon-1.png
    - assets/page-1/images/icon-lock-locked-HUd.png
    - assets/page-1/images/icon-lock-locked-7Tf.png
    - assets/page-1/images/smokquit-logo-1-g7K.png
    - assets/page-1/images/icon-lock-locked-obF.png
    - assets/page-1/images/polygon-1-CMo.png
    - assets/page-1/images/smokquit-logo-1-o61.png
    - assets/page-1/images/icon-lock-locked-YC1.png
    - assets/page-1/images/icon-lock-locked-FAH.png
    - assets/page-1/images/icon-person.png
    - assets/page-1/images/icon-lock-locked-H3o.png
    - assets/page-1/images/smokquit-logo-2.png
    - assets/page-1/images/icon-lock-locked-CMf.png
    - assets/page-1/images/icon-lock-locked-2V7.png
    - assets/page-1/images/group-3.png
    - assets/page-1/images/icon-lock-locked-hD3.png
    - assets/page-1/images/icon-lock-locked-KpV.png
    - assets/page-1/images/icon-lock-locked-VxV.png
    - assets/page-1/images/icon-bell.png
    - assets/page-1/images/icon-lock-locked-VGm.png
    - assets/page-1/images/group-3-ZBP.png
    - assets/page-1/images/auto-group-vh4b.png
    - assets/page-1/images/icon-lock-locked-sRb.png
    - assets/page-1/images/icon-lock-locked-JBT.png
    - assets/page-1/images/icon-lock-locked-wER.png
    - assets/page-1/images/icon-lock-locked-kS5.png
    - assets/page-1/images/icon-grid-three-up.png
    - assets/page-1/images/icon-lock-locked-iBB.png
    - assets/page-1/images/polygon-2.png
    - assets/page-1/images/auto-group-m6bh.png
    - assets/page-1/images/rectangle-66.png
    - assets/page-1/images/auto-group-vcab.png
    - assets/page-1/images/rectangle-67.png
    - assets/page-1/images/icon-lock-locked-oiq.png
    - assets/page-1/images/group-3-r4h.png
    - assets/page-1/images/icon-lock-locked-3ms.png
    - assets/page-1/images/icon-lock-locked-CCq.png
    - assets/page-1/images/icon-calendar.png
    - assets/page-1/images/icon-lock-locked-h8D.png
    - assets/page-1/images/icon-lock-locked-NoK.png
    - assets/page-1/images/auto-group-pcfh.png
    - assets/page-1/images/group-3-sGm.png
    - assets/page-1/images/icon-lock-locked-A8Z.png
    - assets/page-1/images/auto-group-vedd.png
    - assets/page-1/images/group-3-Dy3.png
    - assets/page-1/images/icon-lock-locked-3hj.png
    - assets/page-1/images/icon-lock-locked-ASu.png
    - assets/page-1/images/polygon-2-ZxM.png
    - assets/page-1/images/sq-1.png
    - assets/page-1/images/group-2.png
    - assets/page-1/images/sq-track-1.png
    - assets/page-1/images/auto-group-zwpb.png
    - assets/page-1/images/icon-heart.png
    - assets/page-1/images/sq-1-1.png
    - assets/page-1/images/icon-calendar-Xmb.png
    - assets/model.tflite
    - assets/labels.txt
    - assets/labelss.txt
    - assets/ochna.tflite
    - assets/detect.tflite
    - assets/labelmap.txt
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/mobilenet_v1_1.0_224.txt
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt
    - assets/model_ssd.tflite
    - assets/detectt.tflite
    - assets/hope.tflite
    - assets/rock_paper_scissors_model.tflite
    - assets/quant.tflite
    - assets/it_works.tflite

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
